### PR TITLE
Work flow documentation

### PR DESCRIPTION
**Pull request by ch-pp-rs**
This pretty much includes what we already know. It also has a description of how we are hoping to work with branching and the Delhaize prototyping as well.

Feel free to add comments etc.

### CODE REVIEW

**Comment by muhammaddadu** [comment]
@ch-pp-rs Would it be a good idea to drop the description-text at the end of the Ticket Number for Feature branches to differentiate between Task.

e.g.
**Feature Branch**
```TASK-1```
**Task Branch**
```TASK-1--add-styles```

**Comment by ch-pp-rs** [comment]
@muhammaddadu I would still like a descriptive title for the parent feature. I find it quite frustrating having to look through JIRA to find a ticket. Anyone else got an opinion on this?

**Comment by sophie-vdv** [comment]
@ch-pp-rs @muhammaddadu I agree with Ben

**Comment by fabianfrei** [comment]
@ch-pp-rs Will this document contain the branching strategy for the "main" branches master/e-shop/OLP/POR/PRO in the future?

**Comment by ch-pp-rs** [comment]
@fabianfrei I was planning on putting that in the specific project as that should be pretty unique to that.

**Pull request merged**
